name:        user-service
version:     0.1.0.0
github:      "carp-sushi/user-service"
license:     BSD3
author:      "Carp Sushi"
maintainer:  "105142707+carp-sushi@users.noreply.github.com"
copyright:   "Copyright 2022-present, the original author(s)"
description: Please see the README on GitHub at <https://github.com/carp-sushi/user-service#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - aeson
    - Spock
    - text
    - monad-logger
    - persistent
    - persistent-sqlite
    - persistent-template
    - http-types
    - configurator
    - validation
    - wai

executables:
  user-service-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - user-service
    - aeson
    - Spock
    - text

tests:
  user-service-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - user-service
    - Spock
    - hspec
    - hspec-wai
    - wai
    - tasty
    - tasty-hspec
    - validation
    - text
