resolver: lts-18.15

packages:
- .

extra-deps:
  - Spock-0.14.0.0
  - Spock-core-0.14.0.0
  - Spock-lucid-0.4.0.1
  - reroute-0.6.0.0
  - stm-containers-1.2
  - focus-1.0.1.4
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
